MAXPROJECTILE: int = 5
FIELD_LEFT_BORDER: int = 0
FIELD_RIGHT_BORDER: int = 31
TICK_MOVE_PROJECTILES_DEFAULT: int = 3
TICK_SHOT_PROJECTILE_DEFAULT: int = 3

STATE_PLAY: int = 0
STATE_DEMO: int = 1
STATE_SHOW_WINNER: int = 2
SHIP_LEFT: int = 0
SHIP_RIGHT: int = 1
SHIP_TICK_MOVE: int = 5
SHIP_TICK_SHOT: int = 15

SHIP_ORIENTATION_LEFT: int = 0
SHIP_ORIENTATION_RIGHT: int = 1
SHIP_LEFT_LEFT_BORDER: int = 0
SHIP_LEFT_RIGHT_BORDER: int = 14
SHIP_LEFT_UPPER_BORDER: int = 0
SHIP_LEFT_BOTTOM_BORDER: int = 15
SHIP_RIGHT_LEFT_BORDER: int = 17
SHIP_RIGHT_RIGHT_BORDER: int = 31
SHIP_RIGHT_UPPER_BORDER: int = 0
SHIP_RIGHT_BOTTOM_BORDER: int = 15

BORDER_BOTTOM: int = 15
BORDER_TOP: int = 0
