
# TODO Datei wahrscheinlich nicht benötigt

PIN_COIN_ACCEPTOR_COUNTER = 0

PIN_START_BUTTON = 40

PIN_JOYSTICK_LEFT_LEFT = 51
PIN_JOYSTICK_LEFT_UP = 52
PIN_JOYSTICK_LEFT_RIGHT = 53
PIN_JOYSTICK_LEFT_DOWN = 50
PIN_JOYSTICK_LEFT_BUTTON_TOP = 49
PIN_JOYSTICK_LEFT_BUTTON_BODY = 48

PIN_JOYSTICK_RIGHT_LEFT = 44
PIN_JOYSTICK_RIGHT_UP = 45
PIN_JOYSTICK_RIGHT_DOWN = 47
PIN_JOYSTICK_RIGHT_RIGHT = 46
PIN_JOYSTICK_RIGHT_BUTTON_TOP = 43
PIN_JOYSTICK_RIGHT_BUTTON_BODY = 42

PIN_SIEBEN_SEGMENT_ANZEIGE_1 = 21
PIN_SIEBEN_SEGMENT_ANZEIGE_2 = 20

#/*
# PIN_LED_0 = 33
# PIN_LED_1 = 32
# PIN_LED_2 = 31*/

PIN_LAUTSPRECHER = 30

PIN_DISPLAY_CLK = 11
PIN_DISPLAY_OE = 9
PIN_DISPLAY_B2 = 29
PIN_DISPLAY_G2 = 28
PIN_DISPLAY_R2 = 27
PIN_DISPLAY_B1 = 26
PIN_DISPLAY_G1 = 25
PIN_DISPLAY_R1 = 24

# TODO Rausfinden, was A0 - A3 ist
# TODO Bis dahin, einfach definieren:
A0 = 0
A1 = 1
A2 = 2
A3 = 3
# TODO

PIN_DISPLAY_LAT = A3
PIN_DISPLAY_C = A2
PIN_DISPLAY_B = A1
PIN_DISPLAY_A = A0

RGB_R_PIN = 2
RGB_G_PIN = 3
RGB_B_PIN = 4

# namespace Microcontroller {
#       void init();
# };